<?php

return [
    'version' => '1.0.0',

    'supported_currencies' => ['EUR', 'USD', 'BGN', 'RON', 'PLN', 'CZK', 'HUF'],

    'supported_languages' => ['bg', 'cs', 'da', 'de', 'el', 'en', 'es', 'et', 'fi', 'fr', 'ga', 'hr', 'hu', 'it', 'lt', 'lv', 'mt', 'nl', 'pl', 'pt', 'ro', 'sk', 'sl', 'sv'],

    'locale_names' => [
        'bg' => ['name' => 'Български', 'flag' => '🇧🇬'],
        'cs' => ['name' => 'Čeština', 'flag' => '🇨🇿'],
        'da' => ['name' => 'Dansk', 'flag' => '🇩🇰'],
        'de' => ['name' => 'Deutsch', 'flag' => '🇩🇪'],
        'el' => ['name' => 'Ελληνικά', 'flag' => '🇬🇷'],
        'en' => ['name' => 'English', 'flag' => '🇬🇧'],
        'es' => ['name' => 'Español', 'flag' => '🇪🇸'],
        'et' => ['name' => 'Eesti', 'flag' => '🇪🇪'],
        'fi' => ['name' => 'Suomi', 'flag' => '🇫🇮'],
        'fr' => ['name' => 'Français', 'flag' => '🇫🇷'],
        'ga' => ['name' => 'Gaeilge', 'flag' => '🇮🇪'],
        'hr' => ['name' => 'Hrvatski', 'flag' => '🇭🇷'],
        'hu' => ['name' => 'Magyar', 'flag' => '🇭🇺'],
        'it' => ['name' => 'Italiano', 'flag' => '🇮🇹'],
        'lt' => ['name' => 'Lietuvių', 'flag' => '🇱🇹'],
        'lv' => ['name' => 'Latviešu', 'flag' => '🇱🇻'],
        'mt' => ['name' => 'Malti', 'flag' => '🇲🇹'],
        'nl' => ['name' => 'Nederlands', 'flag' => '🇳🇱'],
        'pl' => ['name' => 'Polski', 'flag' => '🇵🇱'],
        'pt' => ['name' => 'Português', 'flag' => '🇵🇹'],
        'ro' => ['name' => 'Română', 'flag' => '🇷🇴'],
        'sk' => ['name' => 'Slovenčina', 'flag' => '🇸🇰'],
        'sl' => ['name' => 'Slovenščina', 'flag' => '🇸🇮'],
        'sv' => ['name' => 'Svenska', 'flag' => '🇸🇪'],
    ],

    'og_locales' => [
        'bg' => 'bg_BG',
        'cs' => 'cs_CZ',
        'da' => 'da_DK',
        'de' => 'de_DE',
        'el' => 'el_GR',
        'en' => 'en_GB',
        'es' => 'es_ES',
        'et' => 'et_EE',
        'fi' => 'fi_FI',
        'fr' => 'fr_FR',
        'ga' => 'ga_IE',
        'hr' => 'hr_HR',
        'hu' => 'hu_HU',
        'it' => 'it_IT',
        'lt' => 'lt_LT',
        'lv' => 'lv_LV',
        'mt' => 'mt_MT',
        'nl' => 'nl_NL',
        'pl' => 'pl_PL',
        'pt' => 'pt_PT',
        'ro' => 'ro_RO',
        'sk' => 'sk_SK',
        'sl' => 'sl_SI',
        'sv' => 'sv_SE',
    ],
];
