<?php

return [
    'AT' => [
        'available' => true,
        'threshold_amount' => 35000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 35000,
        'legal_basis' => '§6 Abs. 1 Z 27 UStG (Kleinunternehmerregelung)',
        'invoice_notice_local' => 'Gemäß §6 Abs. 1 Z 27 UStG wird keine Umsatzsteuer berechnet.',
        'invoice_notice_en' => 'VAT not charged — exempt under §6 Abs. 1 Z 27 UStG (Austrian small-business exemption).',
    ],
    'BE' => [
        'available' => true,
        'threshold_amount' => 25000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 25000,
        'legal_basis' => 'Art. 56bis BTW-Wetboek / Code TVA',
        'invoice_notice_local' => 'Vrijgesteld van BTW art. 56bis W.BTW / TVA non applicable art. 56bis',
        'invoice_notice_en' => 'VAT not charged — exempt under Art. 56bis of the Belgian VAT Code.',
    ],
    'BG' => [
        'available' => true,
        'threshold_amount' => 100000,
        'threshold_currency' => 'BGN',
        'threshold_eur_approx' => 51000,
        'legal_basis' => 'Art. 96, ал. 1 ЗДДС',
        'invoice_notice_local' => 'Не е начислен ДДС на основание чл. 96, ал. 1 от ЗДДС',
        'invoice_notice_en' => 'VAT not charged pursuant to Art. 96(1) of the Bulgarian VAT Act.',
    ],
    'CY' => [
        'available' => true,
        'threshold_amount' => 15600,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 15600,
        'legal_basis' => 'Article 9 VAT Law 95(I)/2000',
        'invoice_notice_local' => 'VAT not charged — exempt under Article 9 of the VAT Law',
        'invoice_notice_en' => 'VAT not charged — exempt under Article 9 of the VAT Law (Cap. 406).',
    ],
    'CZ' => [
        'available' => true,
        'threshold_amount' => 2000000,
        'threshold_currency' => 'CZK',
        'threshold_eur_approx' => 83000,
        'legal_basis' => '§6 ZDPH (zákon č. 235/2004 Sb.)',
        'invoice_notice_local' => 'Osvobozeno od DPH dle §6 zákona č. 235/2004 Sb.',
        'invoice_notice_en' => 'VAT not charged — exempt under §6 of Czech VAT Act No. 235/2004 Coll.',
    ],
    'DE' => [
        'available' => true,
        'threshold_amount' => 22000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 22000,
        'legal_basis' => '§19 UStG (Kleinunternehmerregelung)',
        'invoice_notice_local' => 'Gemäß §19 UStG wird keine Umsatzsteuer berechnet.',
        'invoice_notice_en' => 'VAT not charged — exempt under §19 UStG (German small-business exemption).',
    ],
    'DK' => [
        'available' => true,
        'threshold_amount' => 50000,
        'threshold_currency' => 'DKK',
        'threshold_eur_approx' => 6700,
        'legal_basis' => '§48 ML (Momsloven)',
        'invoice_notice_local' => 'Fritaget for moms jf. momslovens §48',
        'invoice_notice_en' => 'VAT not charged — exempt under §48 of the Danish VAT Act (Momsloven).',
    ],
    'EE' => [
        'available' => true,
        'threshold_amount' => 40000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 40000,
        'legal_basis' => '§19 KMS (käibemaksuseadus)',
        'invoice_notice_local' => 'Käibemaks ei ole arvestatud vastavalt KMS §19',
        'invoice_notice_en' => 'VAT not charged — exempt under §19 of the Estonian VAT Act (KMS).',
    ],
    'ES' => [
        'available' => false,
        'unavailable_reason' => 'Spain has no general small-business VAT exemption. Spanish freelancers must register for VAT from the first euro of taxable income.',
    ],
    'FI' => [
        'available' => true,
        'threshold_amount' => 15000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 15000,
        'legal_basis' => 'AVL 3 § (arvonlisäverolaki)',
        'invoice_notice_local' => 'ALV:tä ei sovelleta liikevaihdon pienuuden perusteella (AVL 3 §)',
        'invoice_notice_en' => 'VAT not charged — exempt under §3 of the Finnish VAT Act (AVL).',
    ],
    'FR' => [
        'available' => true,
        'threshold_amount' => 36800,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 36800,
        'legal_basis' => 'Art. 293 B CGI (franchise en base de TVA)',
        'invoice_notice_local' => 'TVA non applicable, art. 293 B du CGI',
        'invoice_notice_en' => 'VAT not charged — exempt under Art. 293 B CGI (French small-business exemption).',
    ],
    'GR' => [
        'available' => true,
        'threshold_amount' => 10000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 10000,
        'legal_basis' => 'Art. 39 Κώδικας ΦΠΑ',
        'invoice_notice_local' => 'Απαλλαγή ΦΠΑ βάσει άρθρου 39 Κώδικα ΦΠΑ',
        'invoice_notice_en' => 'VAT not charged — exempt under Article 39 of the Greek VAT Code.',
    ],
    'HR' => [
        'available' => true,
        'threshold_amount' => 40000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 40000,
        'legal_basis' => 'Čl. 90 Zakona o PDV-u',
        'invoice_notice_local' => 'PDV nije obračunat sukladno čl. 90. Zakona o PDV-u',
        'invoice_notice_en' => 'VAT not charged — exempt under Art. 90 of the Croatian VAT Act.',
    ],
    'HU' => [
        'available' => true,
        'threshold_amount' => 12000000,
        'threshold_currency' => 'HUF',
        'threshold_eur_approx' => 33000,
        'legal_basis' => '§188 ÁFA tv. (alanyi adómentesség)',
        'invoice_notice_local' => 'Alanyi adómentes, ÁFA tv. §188. alapján áfa felszámítása nélkül',
        'invoice_notice_en' => 'VAT not charged — exempt under §188 of the Hungarian VAT Act (alanyi adómentesség).',
    ],
    'IE' => [
        'available' => true,
        'threshold_amount' => 37500,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 37500,
        'legal_basis' => 'Section 2(1) VAT Consolidation Act 2010',
        'invoice_notice_local' => 'VAT not charged — exempt under Section 2(1) VAT Consolidation Act 2010',
        'invoice_notice_en' => 'VAT not charged — exempt under Section 2(1) VAT Consolidation Act 2010.',
    ],
    'IT' => [
        'available' => true,
        'threshold_amount' => 85000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 85000,
        'legal_basis' => 'Art. 1 co. 54-89 L. 190/2014 (Regime Forfettario)',
        'invoice_notice_local' => 'Operazione effettuata in regime forfettario ex art. 1 co. 58 L. 190/2014 – imposta non esposta',
        'invoice_notice_en' => 'VAT not charged — flat-rate scheme under Art. 1 co. 54-89 L. 190/2014 (Regime Forfettario).',
    ],
    'LT' => [
        'available' => true,
        'threshold_amount' => 45000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 45000,
        'legal_basis' => 'Art. 71 PVM įstatymo',
        'invoice_notice_local' => 'PVM netaikomas pagal PVM įstatymo 71 str.',
        'invoice_notice_en' => 'VAT not charged — exempt under Art. 71 of the Lithuanian VAT Law.',
    ],
    'LU' => [
        'available' => true,
        'threshold_amount' => 35000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 35000,
        'legal_basis' => 'Art. 57 Loi TVA',
        'invoice_notice_local' => 'TVA non applicable — Art. 57 de la loi TVA',
        'invoice_notice_en' => 'VAT not charged — exempt under Art. 57 of the Luxembourg VAT Law.',
    ],
    'LV' => [
        'available' => true,
        'threshold_amount' => 50000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 50000,
        'legal_basis' => 'Section 64 Pievienotās vērtības nodokļa likums',
        'invoice_notice_local' => 'PVN netiek piemērots saskaņā ar PVN likuma 64. pantu',
        'invoice_notice_en' => 'VAT not charged — exempt under Section 64 of the Latvian VAT Law.',
    ],
    'MT' => [
        'available' => true,
        'threshold_amount' => 20000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 20000,
        'legal_basis' => 'Article 11 VAT Act (Cap. 406)',
        'invoice_notice_local' => 'VAT not charged — exempt under Article 11 of the VAT Act (Cap. 406)',
        'invoice_notice_en' => 'VAT not charged — exempt under Article 11 of the Maltese VAT Act (Cap. 406).',
    ],
    'NL' => [
        'available' => true,
        'threshold_amount' => 20000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 20000,
        'legal_basis' => 'Art. 25 Wet OB (KOR — Kleineondernemersregeling)',
        'invoice_notice_local' => 'Op grond van artikel 25 Wet OB is geen btw gefactureerd.',
        'invoice_notice_en' => 'VAT not charged — exempt under Art. 25 Wet OB (Dutch small-business scheme, KOR).',
    ],
    'PL' => [
        'available' => true,
        'threshold_amount' => 200000,
        'threshold_currency' => 'PLN',
        'threshold_eur_approx' => 47000,
        'legal_basis' => 'Art. 113 ustawy o VAT',
        'invoice_notice_local' => 'Zwolnienie z VAT na podstawie art. 113 ust. 1 ustawy z dnia 11 marca 2004 r. o VAT',
        'invoice_notice_en' => 'VAT not charged — exempt under Art. 113(1) of the Polish VAT Act of 11 March 2004.',
    ],
    'PT' => [
        'available' => true,
        'threshold_amount' => 14500,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 14500,
        'legal_basis' => 'Art. 53.º CIVA',
        'invoice_notice_local' => 'Isento de IVA nos termos do artigo 53.º do CIVA',
        'invoice_notice_en' => 'VAT not charged — exempt under Article 53 of the Portuguese VAT Code (CIVA).',
    ],
    'RO' => [
        'available' => true,
        'threshold_amount' => 300000,
        'threshold_currency' => 'RON',
        'threshold_eur_approx' => 60000,
        'legal_basis' => 'Art. 310 Codul Fiscal (Legea nr. 227/2015)',
        'invoice_notice_local' => 'Scutit de TVA conform art. 310 din Legea nr. 227/2015 – Codul Fiscal',
        'invoice_notice_en' => 'VAT not charged — exempt under Art. 310 of the Romanian Fiscal Code (Law No. 227/2015).',
    ],
    'SE' => [
        'available' => true,
        'threshold_amount' => 80000,
        'threshold_currency' => 'SEK',
        'threshold_eur_approx' => 7000,
        'legal_basis' => '9 d kap. ML (Mervärdesskattelagen)',
        'invoice_notice_local' => 'Mervärdesskatt tas inte ut enligt 9 d kap. ML',
        'invoice_notice_en' => 'VAT not charged — exempt under Chapter 9d of the Swedish VAT Act (ML).',
    ],
    'SI' => [
        'available' => true,
        'threshold_amount' => 50000,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 50000,
        'legal_basis' => 'Art. 94 ZDDV-1',
        'invoice_notice_local' => 'DDV ni obračunan na podlagi 1. odstavka 94. člena ZDDV-1',
        'invoice_notice_en' => 'VAT not charged — exempt under Art. 94(1) of the Slovenian VAT Act (ZDDV-1).',
    ],
    'SK' => [
        'available' => true,
        'threshold_amount' => 49790,
        'threshold_currency' => 'EUR',
        'threshold_eur_approx' => 49790,
        'legal_basis' => '§4 zákona č. 222/2004 Z.z. o DPH',
        'invoice_notice_local' => 'Oslobodené od DPH podľa §4 zákona č. 222/2004 Z.z.',
        'invoice_notice_en' => 'VAT not charged — exempt under §4 of Slovak VAT Act No. 222/2004 Coll.',
    ],
];
